backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img/"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
publish_mode: editorial_workflow
collections:
  # - label: "Blog"
  #   name: "blog"
  #   folder: "src/posts"
  #   create: true
  #   editor:
  #     preview: false
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Description", name: "description", widget: "string" }
  #     - { label: "Author", name: "author", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Body", name: "body", widget: "markdown" }
  #     - widget: select
  #       label: "tags"
  #       name: "tags"
  #       multiple: true
  #       create: true
  #       options: ["Tags", "created", "from", "config.yml"]
  - label: "Arbeitsbeispiele"
    name: "cases"
    folder: "src/cases"
    create: true
    editor:
      preview: false
    sortable_fields: ['title']  
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "MainImage"
        name: mainimg
        widget: object
        required: false
        fields:
          - { label: 'Image', name: 'main_img', widget: 'image', hint: 'Größe 700 x 471 Pixel' } 
          - { label: "Title", name: "title", widget: "string" } 
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Bilder"
        name: galleryimg
        widget: list
        required: false
        fields:
          - { label: 'Image', name: 'gal_img', widget: 'image', hint: 'Höhe 450px, Breite <= 650px' } 
          - { label: "Bildunterschrift", name: "caption", widget: "string", required: false}
          - { label: "Title", name: "title", widget: "string" } 
          - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Meine Aufgabe(n)", name: "mytasks", widget: "markdown" }
      - { label: "Ergebnis", name: "result", widget: "markdown" }
      - name: teaserimg
        label: 'Teaserbild'
        widget: object
        required: false
        fields:
          - { label: 'Teaserbild', name: 'img', widget: 'image', default: '/static/img/klee_teaser_default.jpg', required: false, hint: 'Größe 357 x 271 Pixel' }
          - { label: "Alt Text", name: alt, widget: string }  
      - widget: select
        label: "Leistungen"
        name: "tasks"
        multiple: true
        create: true
        options: ["schreiben", "lektorieren", "faktencheck", "webredaktion"]        
      - label: Weitere Beispiele
        name: caserelprojects
        widget: relation
        collection: cases
        search_fields: ["title"]
        value_field: title 
        display_fields: ["title", "teaserbild.img"]
        required: false
        multiple: true
        max: 3          
  - label: "Pages"
    name: "pages"
    files:
      - label: "Startseite"
        name: "front"
        file: "src/_data/frontpage.yaml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subline, name: subline, widget: markdown}
          - label: Leistungen
            name: services
            widget: list
            fields: 
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - { label: "Body", name: "body", widget: "markdown", required: false } 
              - label: "Symbol"
                name: "icon"
                widget: "select"
                options: 
                  - { label: "Stift", value: "pencil" }
                  - { label: "Buch", value: "book-open" }
                  - { label: "Lupe", value: "search" }
                  - { label: "Computer", value: "desktop-computer" } 
              - label: Beispiele
                name: servicerelprojects
                widget: relation
                collection: cases
                search_fields: ["title"]
                value_field: title 
                display_fields: ["title", "img"]
                required: false
                multiple: true
                max: 3    
          - label: Mein Spezialgebiet
            name: expertise
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" } 
              - { label: "Body", name: "body", widget: "markdown", required: false } 
          - label: Mein Profil
            name: profile
            widget: object
            fields:
              - { label: 'Image', name: 'image', widget: 'image', hint: 'Größe 300 x 300 Pixel' } 
              - { label: "Title", name: "title", widget: "string" } 
              - { label: "Body", name: "body", widget: "markdown", required: true }
              - { label: "ErweiterterText", name: "addtext", widget: "markdown", required: false }
          - label: Kontakt
            name: contact
            widget: object
            fields:
              - { label: "Textblock-Links", name: "textleft", widget: "markdown" } 
              - { label: "Textblock-Rechts", name: "textright", widget: "markdown" }          
      - label: Netzwerk
        name: network
        file: "src/_data/network.yaml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: text, widget: markdown}   
          - label: "Netzwerker"
            name: "partners"
            widget: "list"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Kurzbeschreibung", name: "description", widget: "markdown", required: false }
              - { label: "Website", name: "url", widget: "string", required: false, hint: "Webadresse  mit https://… beginnend" }   
              - label: Bild
                name: img
                widget: object
                allow_multiple: false
                fields:
                  - { label: "Bild", name: "url", widget: "image", hint: 'Größe ca. 450 x 300 Pixel, Querformat bis Quardatisch, kein Hochformat' }
                  - { label: "Alt Text", name: "alt", widget: "string" } 
          - {label: Text, name: text_bottom, widget: markdown}       
      - label: Impressum und Datenschutz
        name: imprint
        file: "src/_data/imprint.yaml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: text, widget: markdown}    
      - label: English Page
        name: english
        file: "src/_data/english.yaml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Text, name: body, widget: markdown}                                    
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
          - { label: Telefonnummer, name: tel, widget: string }
          - { label: E-Mail-Adresse, name: email, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
